Repository 2023-Winter-Bootcamp-Team-I/frontend, pull requests merged in 2024-01, with the labels that each got.

#6 Feat/#3
  public/book.svg
  public/pencil.svg
  src/App.tsx
  src/pages/SignUp.tsx
  src/utils/Routes.tsx
  tailwind.config.js
Labels: ui

#8 Feat/#4 add fonts
  public/book.svg
  public/pencil.svg
  public/vite.svg
  src/assets/fonts/Jua/Jua-Regular.ttf
  src/assets/images/book.svg
  src/assets/images/pencil.svg
  src/assets/images/vite.svg
  src/index.css
  src/index.tsx
  src/pages/SignUp.tsx
  tailwind.config.js
Labels: ui

#12 Feat/#9
  src/assets/images/heart.svg
  src/assets/images/letter.svg
  src/assets/images/lock.svg
  src/components/LogInModal.tsx
  src/pages/SignUp.tsx
  tailwind.config.js
Labels: ui

#14 Feat/#11
  package-lock.json
  package.json
  src/assets/images/Library/Home Page.svg
  src/assets/images/Library/Translation.svg
  src/assets/images/Library/addbook.svg
  src/assets/images/Library/createbook.svg
  src/assets/images/Library/thumbnail.svg
  src/components/BackgroundTemplate.tsx
  src/pages/LibraryPage.tsx
  src/utils/Routes.tsx
  tailwind.config.js
Labels: feature, ui

#16 #13
  src/assets/images/nextButton.svg
  src/assets/images/prevButton.svg
  src/assets/images/robot.svg
  src/pages/FrontCoverPage.tsx
  src/utils/Routes.tsx
  tailwind.config.js
Labels: ui

#20 메인페이지, 로그인 모달 CSS 수정
  src/components/LogInModal.tsx
  src/pages/MainPage.tsx
  src/pages/SignUp.tsx
Labels: bugfix

#18 feat/#17
  src/assets/images/barcode.svg
  src/pages/BackCoverPage.tsx
  src/pages/FrontCoverPage.tsx
  src/utils/Routes.tsx
Labels: ui

#21 feat: 책 생성 페이지 select 커스텀
  src/pages/CreateInfoPage.tsx
  tailwind.config.js
Labels: ui

#23 API URL설정
  .gitignore
  package-lock.json
  package.json
  src/api/api.ts
  src/api/books.ts
Labels: chore

#27 update widths for bookcover pages
  src/pages/BackCoverPage.tsx
  src/pages/FrontCoverPage.tsx
Labels: bugfix, ui

#28 책 생성 페이지, 스토리 선택 모달 css수정 완료
  src/pages/StoryChoiceModal.tsx
Labels: bugfix

#32 update ui
  src/pages/BackCoverPage.tsx
  src/pages/FrontCoverPage.tsx
Labels: bugfix, ui

#39 feat: 제목생성 페이지 퍼블리싱 완료
  src/components/CreateTitleModal.tsx
  src/utils/Routes.tsx
  tailwind.config.js
Labels: feature

#37 Feat/#30
  src/api/books.ts
  src/pages/LibraryPage.tsx
Labels: feature

#42 Bugfix 유저정보페이지 css 수정 완료!!!!
  src/pages/CreateInfoPage.tsx
  src/pages/test.tsx
Labels: bugfix

#46 add delete api for books
  src/api/books.ts
  src/pages/LibraryPage.tsx
Labels: feature

#47 Feat/#43 로그인 모달, 화면전환
  src/components/LogInModal.tsx
  src/pages/BackCoverPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUp.tsx
  src/pages/StoryChoiceModal.tsx
Labels: feature

#49 bugfix/#48
  src/pages/LibraryPage.tsx
  src/pages/test.tsx
Labels: bugfix

#51 #50
  src/pages/LibraryPage.tsx
  src/states/atom.ts
Labels: feature

#54 feat: 서재페이지 공유버튼 추가, 공유 모달페이지 퍼블리싱 완료
  src/assets/images/Close.svg
  src/assets/images/Library/share.svg
  src/assets/images/star.svg
  src/components/ShareModal.tsx
  src/pages/LibraryPage.tsx
  src/utils/Routes.tsx
Labels: ui

#58 Feat/#55 email api연동
  package-lock.json
  package.json
  src/api/email.ts
  src/components/ShareModal.tsx
  src/pages/LibraryPage.tsx
Labels: feature

#61 websocket 로직 구현 및 package.json 충돌해결
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/CreateInfoPage.tsx
  src/pages/FrontCoverPage.tsx
  src/pages/StoryChoiceModal.tsx
  src/pages/test.tsx
  src/states/atom.ts
  src/webSocket.tsx
  src/websocket/WebSocketProvider.tsx
Labels: feature

#63 hover 및 로그아웃시 유저 정보 삭제
  src/components/LogInModal.tsx
  src/components/ShareModal.tsx
  src/pages/LibraryPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUp.tsx
  src/states/atom.ts
  src/utils/Routes.tsx
Labels: feature

#70 Feat/#59
  src/api/books.ts
  src/components/FlipBook.tsx
  src/pages/FrontCoverPage.tsx
  src/pages/ReadBookPage.tsx
  src/utils/Routes.tsx
Labels: feature

#78 로그인 한 상태로 메인가면 버튼 변경, 등록된 id로만 로그인
  package-lock.json
  package.json
  src/components/LogInModal.tsx
  src/components/ShareModal.tsx
  src/pages/CreateInfoPage.tsx
  src/pages/LibraryPage.tsx
  src/pages/MainPage.tsx
Labels: bugfix

#79 메인페이지 framer-motion 적용
  src/components/LogInModal.tsx
  src/pages/LibraryPage.tsx
  src/pages/MainPage.tsx
Labels: ui

#91 feat: 제목 동적으로 할당
  src/components/CreateTitleModal.tsx
  src/pages/CreateInfoPage.tsx
  src/pages/CreationStartPage.tsx
  src/pages/StoryChoiceModal.tsx
  src/states/atom.ts
Labels: bugfix

#87 sweetalert 수정 및 버튼 테두리, 동화색 선택 오류 해결
  package-lock.json
  package.json
  src/api/email.ts
  src/api/login.ts
  src/api/users.ts
  src/components/LogInModal.tsx
  src/components/ShareModal.tsx
  src/pages/CreateInfoPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUp.tsx
Labels: bugfix, feature

#84 bugfix/#83 책 삭제 후 리스트에 바로 반영
  src/pages/LibraryPage.tsx
Labels: bugfix

#94 Feat/#85
  src/api/books.ts
  src/components/ContentPage.tsx
  src/components/FlipBook.tsx
  src/components/FrontCover.tsx
  src/pages/FrontCoverPage.tsx
  src/pages/LibraryPage.tsx
  src/utils/Routes.tsx
Labels: bugfix, feature

#97 framer-motion 및 모달창, 버튼 수정
  src/components/LogInModal.tsx
  src/pages/MainPage.tsx
Labels: bugfix, ui

#101 feat/#100/contentpage css
  src/components/ContentPage.tsx
Labels: ui

#105 메인페이지 애니메이션 수정 및 서재페이지 수정
  src/pages/BackCoverPage.tsx
  src/pages/CreateInfoPage.tsx
  src/pages/CreationStartPage.tsx
  src/pages/LibraryPage.tsx
  src/pages/MainPage.tsx
  src/pages/ReadBookPage.tsx
  src/pages/StoryChoiceModal.tsx
Labels: ui

#107 feat/#106 tts 버튼 추가
  package-lock.json
  package.json
  src/api/books.ts
  src/assets/images/ttsButton.svg
  src/components/ContentPage.tsx
  src/pages/FrontCoverPage.tsx
  src/pages/StoryChoiceModal.tsx
Labels: feature

#111 서재 페이지 썸네일 수정
  src/pages/LibraryPage.tsx
Labels: bugfix

#114 i18n
  src/i18n.ts
  src/pages/CreateBookPage.tsx
  src/pages/CreateInfoPage.tsx
  src/pages/CreationStartPage.tsx
  src/pages/LoadingPage.tsx
  src/pages/MainPage.tsx
  src/pages/StoryChoiceModal.tsx
  src/states/atom.ts
  src/utils/Routes.tsx
Labels: feature

#116 서재 페이지 썸네일 css 수정
  src/pages/LibraryPage.tsx
Labels: bugfix, ui

#117 스토리 선택 모달 디자인 변경 및 로딩페이지 수정
  src/pages/LoadingPage.tsx
  src/pages/StoryChoiceModal.tsx
Labels: bugfix

#120 bugfix/#119
  index.html
  src/pages/ReadBookPage.tsx
Labels: ui

#123 add nav bar
  src/components/NavBar.tsx
  src/pages/BackCoverPage.tsx
  src/pages/FrontCoverPage.tsx
  src/pages/LibraryPage.tsx
Labels: feature

#125 오류코드 해결
  src/@types/use-sound/index.d.ts
  src/pages/CreationFinishPage.tsx
  src/pages/CreationStartPage.tsx
  src/pages/LibraryPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUp.tsx
  src/pages/test.tsx
  src/webSocket.tsx
  tsconfig.json
Labels: bugfix

#124 유저정보 페이지 수정
  src/assets/image/CreateInfo/input1.png
  src/assets/image/CreateInfo/input2.png
  src/assets/image/CreateInfo/typing.svg
  src/i18n.ts
  src/pages/CreateInfoPage.tsx
Labels: ui
